# Generated by Django 5.0.6 on 2024-06-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='member_rankings',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
