# Generated by Django 5.0.6 on 2024-06-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmanager', '0003_remove_club_member_rankings_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.IntegerField(),
        ),
    ]
