# Generated by Django 5.0.6 on 2024-06-13 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmanager', '0004_member_score_alter_member_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('elapsed_time', models.TimeField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('buy_in', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='ranking',
            field=models.FloatField(default=999999),
        ),
        migrations.AddField(
            model_name='club',
            name='games',
            field=models.ManyToManyField(related_name='club_games', to='clubmanager.game'),
        ),
    ]
