# Generated by Django 5.0.6 on 2024-06-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmanager', '0008_game_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('num_players', models.IntegerField()),
                ('starting_stack', models.IntegerField()),
                ('small_blind', models.IntegerField()),
                ('target_duration', models.FloatField()),
                ('blind_duration', models.IntegerField()),
                ('players', models.ManyToManyField(to='clubmanager.member')),
            ],
        ),
    ]
