# Generated by Django 5.0.6 on 2024-06-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmanager', '0010_alter_tournament_num_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='tournaments',
            field=models.ManyToManyField(related_name='club_tournaments', to='clubmanager.tournament'),
        ),
    ]
