# Generated by Django 5.0.6 on 2024-06-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmanager', '0011_club_tournaments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='num_players',
        ),
        migrations.AddField(
            model_name='tournament',
            name='blind_structure',
            field=models.JSONField(default=list),
        ),
    ]
