# Generated by Django 5.0.6 on 2024-06-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmanager', '0012_remove_tournament_num_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_scores',
            field=models.JSONField(default=dict),
        ),
    ]
