# Generated by Django 5.0.6 on 2024-07-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmanager', '0013_game_player_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_buy_ins',
            field=models.JSONField(default=dict),
        ),
    ]
