# Generated by Django 5.0.6 on 2024-07-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmanager', '0014_game_player_buy_ins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='buy_in',
            field=models.IntegerField(),
        ),
    ]
