# Generated by Django 5.0.6 on 2024-08-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmanager', '0019_alter_member_created_user_alter_member_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createduser',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='createduser',
            name='last_name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
