# Generated by Django 5.0.6 on 2024-08-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmanager', '0020_rename_name_createduser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createduser',
            name='first_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='createduser',
            name='last_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
