# Generated by Django 5.0.6 on 2024-08-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmanager', '0023_alter_createduser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createduser',
            name='first_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='createduser',
            name='last_name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
