# Generated by Django 5.0.6 on 2024-08-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmanager', '0025_alter_createduser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createduser',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, verbose_name='email address'),
        ),
    ]
