# Generated by Django 5.0.6 on 2024-08-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmanager', '0031_alter_createduser_email_alter_createduser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createduser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='createduser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
