# Generated by Django 5.0.6 on 2024-06-03 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number', regex='^(\\d{10}|\\d{3}-\\d{3}-\\d{4})$')]),
        ),
    ]
